/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { CreateFileRoute, FileRoutesByPath } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewRouteImport } from './routes/new'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GroupIndexRouteImport } from './routes/group/index'
import { Route as GroupRoomIdroomIdIndexRouteImport } from './routes/group/$roomId/(roomId)/index'
import { Route as GroupRoomIdshareShareRouteImport } from './routes/group/$roomId/(share)/share'
import { Route as GroupRoomIdresultResultRouteImport } from './routes/group/$roomId/(result)/result'

const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupIndexRoute = GroupIndexRouteImport.update({
  id: '/group/',
  path: '/group/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupRoomIdroomIdIndexRoute = GroupRoomIdroomIdIndexRouteImport.update({
  id: '/group/$roomId/(roomId)/',
  path: '/group/$roomId/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupRoomIdshareShareRoute = GroupRoomIdshareShareRouteImport.update({
  id: '/group/$roomId/(share)/share',
  path: '/group/$roomId/share',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupRoomIdresultResultRoute = GroupRoomIdresultResultRouteImport.update({
  id: '/group/$roomId/(result)/result',
  path: '/group/$roomId/result',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/group': typeof GroupIndexRoute
  '/group/$roomId/result': typeof GroupRoomIdresultResultRoute
  '/group/$roomId/share': typeof GroupRoomIdshareShareRoute
  '/group/$roomId': typeof GroupRoomIdroomIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/group': typeof GroupIndexRoute
  '/group/$roomId/result': typeof GroupRoomIdresultResultRoute
  '/group/$roomId/share': typeof GroupRoomIdshareShareRoute
  '/group/$roomId': typeof GroupRoomIdroomIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/group/': typeof GroupIndexRoute
  '/group/$roomId/(result)/result': typeof GroupRoomIdresultResultRoute
  '/group/$roomId/(share)/share': typeof GroupRoomIdshareShareRoute
  '/group/$roomId/(roomId)/': typeof GroupRoomIdroomIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/new'
    | '/group'
    | '/group/$roomId/result'
    | '/group/$roomId/share'
    | '/group/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/new'
    | '/group'
    | '/group/$roomId/result'
    | '/group/$roomId/share'
    | '/group/$roomId'
  id:
    | '__root__'
    | '/'
    | '/new'
    | '/group/'
    | '/group/$roomId/(result)/result'
    | '/group/$roomId/(share)/share'
    | '/group/$roomId/(roomId)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewRoute: typeof NewRoute
  GroupIndexRoute: typeof GroupIndexRoute
  GroupRoomIdresultResultRoute: typeof GroupRoomIdresultResultRoute
  GroupRoomIdshareShareRoute: typeof GroupRoomIdshareShareRoute
  GroupRoomIdroomIdIndexRoute: typeof GroupRoomIdroomIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group/': {
      id: '/group/'
      path: '/group'
      fullPath: '/group'
      preLoaderRoute: typeof GroupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group/$roomId/(result)/result': {
      id: '/group/$roomId/(result)/result'
      path: '/group/$roomId/result'
      fullPath: '/group/$roomId/result'
      preLoaderRoute: typeof GroupRoomIdresultResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group/$roomId/(share)/share': {
      id: '/group/$roomId/(share)/share'
      path: '/group/$roomId/share'
      fullPath: '/group/$roomId/share'
      preLoaderRoute: typeof GroupRoomIdshareShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group/$roomId/(roomId)/': {
      id: '/group/$roomId/(roomId)/'
      path: '/group/$roomId'
      fullPath: '/group/$roomId'
      preLoaderRoute: typeof GroupRoomIdroomIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group/$roomId/(roomId)/components/BulkPlateModal': {
      id: '/group/$roomId/(roomId)/components/BulkPlateModal'
      path: ''
      fullPath: '/group/$roomId/components/BulkPlateModal'
      preLoaderRoute: unknown
      parentRoute: typeof rootRouteImport
    }
    '/group/$roomId/(roomId)/components/EditPlateModal': {
      id: '/group/$roomId/(roomId)/components/EditPlateModal'
      path: ''
      fullPath: '/group/$roomId/components/EditPlateModal'
      preLoaderRoute: unknown
      parentRoute: typeof rootRouteImport
    }
    '/group/$roomId/(roomId)/components/GroupSummary': {
      id: '/group/$roomId/(roomId)/components/GroupSummary'
      path: ''
      fullPath: '/group/$roomId/components/GroupSummary'
      preLoaderRoute: unknown
      parentRoute: typeof rootRouteImport
    }
    '/group/$roomId/(roomId)/components/MemberList': {
      id: '/group/$roomId/(roomId)/components/MemberList'
      path: ''
      fullPath: '/group/$roomId/components/MemberList'
      preLoaderRoute: unknown
      parentRoute: typeof rootRouteImport
    }
    '/group/$roomId/(roomId)/components/PlateTemplateEditor': {
      id: '/group/$roomId/(roomId)/components/PlateTemplateEditor'
      path: ''
      fullPath: '/group/$roomId/components/PlateTemplateEditor'
      preLoaderRoute: unknown
      parentRoute: typeof rootRouteImport
    }
    '/group/$roomId/(roomId)/components/RankNotifications': {
      id: '/group/$roomId/(roomId)/components/RankNotifications'
      path: ''
      fullPath: '/group/$roomId/components/RankNotifications'
      preLoaderRoute: unknown
      parentRoute: typeof rootRouteImport
    }
    '/group/$roomId/(roomId)/components/ShareButton': {
      id: '/group/$roomId/(roomId)/components/ShareButton'
      path: ''
      fullPath: '/group/$roomId/components/ShareButton'
      preLoaderRoute: unknown
      parentRoute: typeof rootRouteImport
    }
  }
}

declare module './routes/index' {
  const createFileRoute: CreateFileRoute<
    '/',
    FileRoutesByPath['/']['parentRoute'],
    FileRoutesByPath['/']['id'],
    FileRoutesByPath['/']['path'],
    FileRoutesByPath['/']['fullPath']
  >
}
declare module './routes/new' {
  const createFileRoute: CreateFileRoute<
    '/new',
    FileRoutesByPath['/new']['parentRoute'],
    FileRoutesByPath['/new']['id'],
    FileRoutesByPath['/new']['path'],
    FileRoutesByPath['/new']['fullPath']
  >
}
declare module './routes/group/index' {
  const createFileRoute: CreateFileRoute<
    '/group/',
    FileRoutesByPath['/group/']['parentRoute'],
    FileRoutesByPath['/group/']['id'],
    FileRoutesByPath['/group/']['path'],
    FileRoutesByPath['/group/']['fullPath']
  >
}
declare module './routes/group/$roomId/(result)/result' {
  const createFileRoute: CreateFileRoute<
    '/group/$roomId/(result)/result',
    FileRoutesByPath['/group/$roomId/(result)/result']['parentRoute'],
    FileRoutesByPath['/group/$roomId/(result)/result']['id'],
    FileRoutesByPath['/group/$roomId/(result)/result']['path'],
    FileRoutesByPath['/group/$roomId/(result)/result']['fullPath']
  >
}
declare module './routes/group/$roomId/(share)/share' {
  const createFileRoute: CreateFileRoute<
    '/group/$roomId/(share)/share',
    FileRoutesByPath['/group/$roomId/(share)/share']['parentRoute'],
    FileRoutesByPath['/group/$roomId/(share)/share']['id'],
    FileRoutesByPath['/group/$roomId/(share)/share']['path'],
    FileRoutesByPath['/group/$roomId/(share)/share']['fullPath']
  >
}
declare module './routes/group/$roomId/(roomId)/index' {
  const createFileRoute: CreateFileRoute<
    '/group/$roomId/(roomId)/',
    FileRoutesByPath['/group/$roomId/(roomId)/']['parentRoute'],
    FileRoutesByPath['/group/$roomId/(roomId)/']['id'],
    FileRoutesByPath['/group/$roomId/(roomId)/']['path'],
    FileRoutesByPath['/group/$roomId/(roomId)/']['fullPath']
  >
}
declare module './routes/group/$roomId/(roomId)/components/BulkPlateModal' {
  const createFileRoute: CreateFileRoute<
    '/group/$roomId/(roomId)/components/BulkPlateModal',
    FileRoutesByPath['/group/$roomId/(roomId)/components/BulkPlateModal']['parentRoute'],
    FileRoutesByPath['/group/$roomId/(roomId)/components/BulkPlateModal']['id'],
    FileRoutesByPath['/group/$roomId/(roomId)/components/BulkPlateModal']['path'],
    FileRoutesByPath['/group/$roomId/(roomId)/components/BulkPlateModal']['fullPath']
  >
}
declare module './routes/group/$roomId/(roomId)/components/EditPlateModal' {
  const createFileRoute: CreateFileRoute<
    '/group/$roomId/(roomId)/components/EditPlateModal',
    FileRoutesByPath['/group/$roomId/(roomId)/components/EditPlateModal']['parentRoute'],
    FileRoutesByPath['/group/$roomId/(roomId)/components/EditPlateModal']['id'],
    FileRoutesByPath['/group/$roomId/(roomId)/components/EditPlateModal']['path'],
    FileRoutesByPath['/group/$roomId/(roomId)/components/EditPlateModal']['fullPath']
  >
}
declare module './routes/group/$roomId/(roomId)/components/GroupSummary' {
  const createFileRoute: CreateFileRoute<
    '/group/$roomId/(roomId)/components/GroupSummary',
    FileRoutesByPath['/group/$roomId/(roomId)/components/GroupSummary']['parentRoute'],
    FileRoutesByPath['/group/$roomId/(roomId)/components/GroupSummary']['id'],
    FileRoutesByPath['/group/$roomId/(roomId)/components/GroupSummary']['path'],
    FileRoutesByPath['/group/$roomId/(roomId)/components/GroupSummary']['fullPath']
  >
}
declare module './routes/group/$roomId/(roomId)/components/MemberList' {
  const createFileRoute: CreateFileRoute<
    '/group/$roomId/(roomId)/components/MemberList',
    FileRoutesByPath['/group/$roomId/(roomId)/components/MemberList']['parentRoute'],
    FileRoutesByPath['/group/$roomId/(roomId)/components/MemberList']['id'],
    FileRoutesByPath['/group/$roomId/(roomId)/components/MemberList']['path'],
    FileRoutesByPath['/group/$roomId/(roomId)/components/MemberList']['fullPath']
  >
}
declare module './routes/group/$roomId/(roomId)/components/PlateTemplateEditor' {
  const createFileRoute: CreateFileRoute<
    '/group/$roomId/(roomId)/components/PlateTemplateEditor',
    FileRoutesByPath['/group/$roomId/(roomId)/components/PlateTemplateEditor']['parentRoute'],
    FileRoutesByPath['/group/$roomId/(roomId)/components/PlateTemplateEditor']['id'],
    FileRoutesByPath['/group/$roomId/(roomId)/components/PlateTemplateEditor']['path'],
    FileRoutesByPath['/group/$roomId/(roomId)/components/PlateTemplateEditor']['fullPath']
  >
}
declare module './routes/group/$roomId/(roomId)/components/RankNotifications' {
  const createFileRoute: CreateFileRoute<
    '/group/$roomId/(roomId)/components/RankNotifications',
    FileRoutesByPath['/group/$roomId/(roomId)/components/RankNotifications']['parentRoute'],
    FileRoutesByPath['/group/$roomId/(roomId)/components/RankNotifications']['id'],
    FileRoutesByPath['/group/$roomId/(roomId)/components/RankNotifications']['path'],
    FileRoutesByPath['/group/$roomId/(roomId)/components/RankNotifications']['fullPath']
  >
}
declare module './routes/group/$roomId/(roomId)/components/ShareButton' {
  const createFileRoute: CreateFileRoute<
    '/group/$roomId/(roomId)/components/ShareButton',
    FileRoutesByPath['/group/$roomId/(roomId)/components/ShareButton']['parentRoute'],
    FileRoutesByPath['/group/$roomId/(roomId)/components/ShareButton']['id'],
    FileRoutesByPath['/group/$roomId/(roomId)/components/ShareButton']['path'],
    FileRoutesByPath['/group/$roomId/(roomId)/components/ShareButton']['fullPath']
  >
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewRoute: NewRoute,
  GroupIndexRoute: GroupIndexRoute,
  GroupRoomIdresultResultRoute: GroupRoomIdresultResultRoute,
  GroupRoomIdshareShareRoute: GroupRoomIdshareShareRoute,
  GroupRoomIdroomIdIndexRoute: GroupRoomIdroomIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
